### ISSUE TITLE
没有softmax 操作

### ISSUE THREAD

**Issue by Ericargus** [Hsuxu/FocalLoss-PyTorch#1]
你好，我看了你的代码之后，发现你直接对input 做了log操作，而没有用softmax将input映射为概率值在进行log操作， 这与公式不符。这仅为个人观点，如有错误，望指正，谢谢。

**Comment by Hsuxu** [comment]
input即为概率分布，接受的是softmax的结果。这样是否有问题

**Comment by Ericargus** [comment]
哦，我知道你的意思了
